"""updated events to allow custom events

Revision ID: 1775478475
Revises: 1775320001
Create Date: 2026-04-06 13:27:55.556593

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1775478475"
down_revision: Union[str, Sequence[str], None] = "1775320001"
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column(
            "event_source",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.Enum("CUSTOM", name="eventsource"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "image_url", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.alter_column(
            "external_id", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.drop_column("video_url")
        batch_op.drop_column("capacity")

    op.execute(
        "UPDATE events SET event_source = 'CUSTOM' WHERE event_source IS NULL OR event_source = ''"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("capacity", sa.INTEGER(), nullable=False))
        batch_op.add_column(
            sa.Column("video_url", sa.VARCHAR(length=255), nullable=True)
        )
        batch_op.alter_column(
            "external_id", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column(
            "image_url", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column(
            "event_source",
            existing_type=sa.Enum("CUSTOM", name="eventsource"),
            type_=sa.VARCHAR(length=255),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
