"""added_anon_trips

Revision ID: 027ba6ee3071
Revises: 05050ecb32be
Create Date: 2026-09-13 19:40:14.727198

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "027ba6ee3071"
down_revision = "05050ecb32be"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("itineraries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_anonymous", sa.Boolean(), nullable=False))
        batch_op.add_column(
            sa.Column("anonymous_access_code", sa.String(length=255), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("itineraries", schema=None) as batch_op:
        batch_op.drop_column("anonymous_access_code")
        batch_op.drop_column("is_anonymous")

    # ### end Alembic commands ###
