"""added_timezones

Revision ID: 05050ecb32be
Revises: e8d90f12a3b4
Create Date: 2026-09-03 14:01:40.271376

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "05050ecb32be"
down_revision = "e8d90f12a3b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("itineraries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("timezone", sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("itineraries", schema=None) as batch_op:
        batch_op.drop_column("timezone")

    # ### end Alembic commands ###
