"""added events and itinerary_events association table

Revision ID: 1775320001
Revises: 1775316375
Create Date: 2026-04-04 17:26:41.294352

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1775320001"
down_revision: Union[str, Sequence[str], None] = "1775316375"
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("location", sa.String(length=256), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("category", sa.String(length=256), nullable=False),
        sa.Column("min_age", sa.Integer(), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column(
            "event_status",
            sa.Enum("ACTIVE", "CANCELLED", "POSTPONED", name="eventstatus"),
            nullable=False,
        ),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("event_source", sa.String(length=255), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=False),
        sa.Column("video_url", sa.String(length=255), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("last_sync", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_id"),
    )
    op.create_table(
        "itinerary_events",
        sa.Column("itinerary_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["itinerary_id"], ["itineraries.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("itinerary_id", "event_id"),
    )
    with op.batch_alter_table("itinerary_users", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(length=6),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("itinerary_users", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(length=6),
            server_default=sa.text("'ADMIN'"),
            existing_nullable=False,
        )

    op.drop_table("itinerary_events")
    op.drop_table("events")
    # ### end Alembic commands ###
