"""Added role to itinerary_user table

Revision ID: 1775316375
Revises: 1775302033
Create Date: 2026-04-04 16:26:15.125816

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1775316375"
down_revision: Union[str, Sequence[str], None] = "1775302033"
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("itinerary_users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "role",
                sa.Enum("ADMIN", "EDITOR", "VIEWER", name="userrole"),
                nullable=False,
                server_default="ADMIN",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("itinerary_users", schema=None) as batch_op:
        batch_op.drop_column("role")

    # ### end Alembic commands ###
