"""added_unique_constraint_to_invite

Revision ID: 4b86e78ffdcc
Revises: 36ef9424acff
Create Date: 2026-06-20 03:30:57.251798

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "4b86e78ffdcc"
down_revision = "36ef9424acff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("itinerary_invitations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("token"))
        batch_op.create_unique_constraint(
            "uq_invite_email_itinerary", ["email", "itinerary_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("itinerary_invitations", schema=None) as batch_op:
        batch_op.drop_constraint("uq_invite_email_itinerary", type_="unique")
        batch_op.create_index(batch_op.f("token"), ["token"], unique=True)

    # ### end Alembic commands ###
