"""added_anon_trips

Revision ID: 5b85d7a702a4
Revises: 05050ecb32be
Create Date: 2026-09-13 22:07:01.045325

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b85d7a702a4"
down_revision = "05050ecb32be"
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("itineraries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "anonymous_access_code",
                sa.String(length=255),
                nullable=True,
                server_default=sa.false(),
            )
        )
        batch_op.add_column(sa.Column("is_anonymous", sa.Boolean(), nullable=True))

    op.execute("UPDATE itineraries SET is_anonymous = 0 WHERE is_anonymous IS NULL")

    with op.batch_alter_table("itineraries", schema=None) as batch_op:
        batch_op.alter_column(
            "is_anonymous",
            existing_type=sa.Boolean(),
            nullable=False,
        )

        # Your other column changes can remain here


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("itineraries", schema=None) as batch_op:
        batch_op.drop_column("anonymous_access_code")
        batch_op.drop_column("is_anonymous")

    # ### end Alembic commands ###
