"""final audit schema fix

Revision ID: 8184c4bd2559
Revises: c84ba1f6ccb8
Create Date: 2026-04-08 17:32:32.890401

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8184c4bd2559"
down_revision = "c84ba1f6ccb8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("created_by_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("updated_by_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_events_external_id"), ["external_id"], unique=True
        )
        batch_op.create_foreign_key(
            "fk_events_created_by", "users", ["created_by_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_events_updated_by", "users", ["updated_by_id"], ["id"]
        )

    with op.batch_alter_table("itineraries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("created_by_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("updated_by_id", sa.Integer(), nullable=True))
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATE(),
            type_=sa.DateTime(),
            existing_nullable=False,
        )
        batch_op.create_index(
            batch_op.f("ix_itineraries_start_date"), ["start_date"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_itineraries_created_by", "users", ["created_by_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_itineraries_updated_by", "users", ["updated_by_id"], ["id"]
        )

    with op.batch_alter_table("itinerary_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("created_by_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("updated_by_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_itinerary_events_created_by", "users", ["created_by_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_itinerary_events_updated_by", "users", ["updated_by_id"], ["id"]
        )

    with op.batch_alter_table("itinerary_invitations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("created_by_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("updated_by_id", sa.Integer(), nullable=True))
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.Enum("admin", "editor", "viewer", name="userrole"),
            existing_nullable=False,
        )
        batch_op.create_index(
            batch_op.f("ix_itinerary_invitations_email"), ["email"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_itinerary_invitations_token"), ["token"], unique=True
        )
        batch_op.create_foreign_key(
            "fk_itinerary_invitations_created_by", "users", ["updated_by_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_itinerary_invitations_updated_by", "users", ["created_by_id"], ["id"]
        )

    with op.batch_alter_table("itinerary_users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("created_by_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("updated_by_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_itinerary_users_created_by", "users", ["created_by_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_itinerary_invitations_updated_by", "users", ["updated_by_id"], ["id"]
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("itinerary_users", schema=None) as batch_op:
        batch_op.drop_constraint("fk_itinerary_users_created_by", type_="foreignkey")
        batch_op.drop_constraint(
            "fk_itinerary_invitations_updated_by", type_="foreignkey"
        )
        batch_op.drop_column("updated_by_id")
        batch_op.drop_column("created_by_id")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("itinerary_invitations", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_itinerary_invitations_created_by", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_itinerary_invitations_updated_by", type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_itinerary_invitations_token"))
        batch_op.drop_index(batch_op.f("ix_itinerary_invitations_email"))
        batch_op.alter_column(
            "role",
            existing_type=sa.Enum("admin", "editor", "viewer", name="userrole"),
            type_=sa.VARCHAR(length=20),
            existing_nullable=False,
        )
        batch_op.drop_column("updated_by_id")
        batch_op.drop_column("created_by_id")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("itinerary_events", schema=None) as batch_op:
        batch_op.drop_constraint("fk_itinerary_events_created_by", type_="foreignkey")
        batch_op.drop_constraint("fk_itinerary_events_updated_by", type_="foreignkey")
        batch_op.drop_column("updated_by_id")
        batch_op.drop_column("created_by_id")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    with op.batch_alter_table("itineraries", schema=None) as batch_op:
        batch_op.drop_constraint("fk_itineraries_updated_by", type_="foreignkey")
        batch_op.drop_constraint("fk_itineraries_created_by", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_itineraries_start_date"))
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DateTime(),
            type_=sa.DATE(),
            existing_nullable=False,
        )
        batch_op.drop_column("updated_by_id")
        batch_op.drop_column("created_by_id")
        batch_op.drop_column("updated_at")

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_constraint("fk_events_updated_by", type_="foreignkey")
        batch_op.drop_constraint("fk_events_created_by", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_events_external_id"))
        batch_op.drop_column("updated_by_id")
        batch_op.drop_column("created_by_id")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
