"""Added location to itinerary

Revision ID: 869e47969cb7
Revises: 86b2dd2c7b32
Create Date: 2026-04-22 23:01:52.665358

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "869e47969cb7"
down_revision = "86b2dd2c7b32"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("itineraries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "destination",
                sa.String(length=255),
                nullable=False,
                server_default="London",
            )
        )
        batch_op.add_column(
            sa.Column("latitude", sa.Float(), nullable=False, server_default="51.5072")
        )
        batch_op.add_column(
            sa.Column("longitude", sa.Float(), nullable=False, server_default="-0.1276")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("itineraries", schema=None) as batch_op:
        batch_op.drop_column("longitude")
        batch_op.drop_column("latitude")
        batch_op.drop_column("destination")

    # ### end Alembic commands ###
