"""Split location field into name, address, longitude and latitude

Revision ID: 86b2dd2c7b32
Revises: 8a05caa1b377
Create Date: 2026-04-21 22:26:20.561816

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "86b2dd2c7b32"
down_revision = "8a05caa1b377"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("DELETE FROM events")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column("address", sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column("latitude", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("longitude", sa.Float(), nullable=False))
        batch_op.drop_column("location")

    # ### end Alembic commands ###


def downgrade():
    op.execute("DELETE FROM events")
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("location", mysql.VARCHAR(length=256), nullable=False)
        )
        batch_op.drop_column("longitude")
        batch_op.drop_column("latitude")
        batch_op.drop_column("address")
        batch_op.drop_column("name")

    # ### end Alembic commands ###
