"""simplified event model

Revision ID: 8a05caa1b377
Revises: 8184c4bd2559
Create Date: 2026-04-17 22:13:22.572621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a05caa1b377'
down_revision = '8184c4bd2559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_at', sa.DateTime(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_events_external_id'))
        batch_op.drop_column('image_url')
        batch_op.drop_column('event_status')
        batch_op.drop_column('event_source')
        batch_op.drop_column('start_time')
        batch_op.drop_column('external_id')
        batch_op.drop_column('min_age')
        batch_op.drop_column('end_time')
        batch_op.drop_column('name')
        batch_op.drop_column('price')
        batch_op.drop_column('last_sync')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sync', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('min_age', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('external_id', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('event_source', sa.VARCHAR(length=6), nullable=False))
        batch_op.add_column(sa.Column('event_status', sa.VARCHAR(length=9), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_events_external_id'), ['external_id'], unique=1)
        batch_op.drop_column('end_at')
        batch_op.drop_column('start_at')

    # ### end Alembic commands ###
