"""added_wishlist_item_votes

Revision ID: 99565612f051
Revises: aa4658f7ddf9
Create Date: 2026-08-06 22:16:56.732970

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "99565612f051"
down_revision = "aa4658f7ddf9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wishlist_item_votes",
        sa.Column("wishlist_item_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("isThumbsUp", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["wishlist_item_id"], ["wishlist_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("wishlist_item_id", "user_id"),
    )
    with op.batch_alter_table("wishlist_item_votes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_wishlist_item_votes_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_wishlist_item_votes_wishlist_item_id"),
            ["wishlist_item_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("wishlist_item_votes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wishlist_item_votes_wishlist_item_id"))
        batch_op.drop_index(batch_op.f("ix_wishlist_item_votes_user_id"))

    op.drop_table("wishlist_item_votes")
    # ### end Alembic commands ###
