"""added_packing_items

Revision ID: aa4658f7ddf9
Revises: fee8c9c76d19
Create Date: 2026-07-16 21:19:13.781333

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aa4658f7ddf9"
down_revision = "fee8c9c76d19"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "packing_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("itinerary_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("is_shared", sa.Boolean(), nullable=False),
        sa.Column("is_checked", sa.Boolean(), nullable=False),
        sa.Column("checked_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["checked_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["itinerary_id"], ["itineraries.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("packing_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_packing_items_itinerary_id"), ["itinerary_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_packing_items_owner_id"), ["owner_id"], unique=False
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("packing_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_packing_items_owner_id"))
        batch_op.drop_index(batch_op.f("ix_packing_items_itinerary_id"))

    op.drop_table("packing_items")
    # ### end Alembic commands ###
