"""added_accommodations

Revision ID: fee8c9c76d19
Revises: ffbb61b5d388
Create Date: 2026-07-12 17:37:31.447139

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fee8c9c76d19"
down_revision = "ffbb61b5d388"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accommodations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("itinerary_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["itinerary_id"], ["itineraries.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("accommodations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_accommodations_itinerary_id"), ["itinerary_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_accommodations_start_date"), ["start_date"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accommodations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accommodations_start_date"))
        batch_op.drop_index(batch_op.f("ix_accommodations_itinerary_id"))

    op.drop_table("accommodations")
    # ### end Alembic commands ###
